<?php
/**
 * @file
 *  Code for DAMS module.
 */

/**
 * Implements hook_menu().
 */
function easyddb_dams_menu() {
  $items = array();

  $items['admin/easyddb_dams_media_manager'] = array(
    'title' => 'Media manager',
    'description' => 'Upload and manage the media library',
    'page arguments' => array(),
    'page callback' => 'easyddb_dams_media_manager_page',
    'access arguments' => array('administer files'),
    'type' => MENU_NORMAL_ITEM,
  );

  return $items;
}

/**
 * Media manager page.
 */
function easyddb_dams_media_manager_page() {
  $content = '';

  if (module_exists('media')) {
    module_load_include('inc', 'media', 'includes/media.browser');
    $content = media_browser();
  }

  return $content;
}

/**
 * Implements hook_page_alter().
 */
function easyddb_dams_page_alter(&$page) {
  if (arg(0) == 'admin' && arg(1) == 'easyddb_dams_media_manager') {
    $page['#theme'] = 'media_dialog_page';
  }
}

/**
 * Implements hook_form_alter().
 */
function easyddb_dams_form_alter(&$form, &$form_state, $form_id) {
  if ($form_id == 'file_entity_add_upload' && arg(1) == 'easyddb_dams_media_manager') {
    array_unshift($form['#submit'], 'easyddb_dams_add_upload_submit');
  }
}

/**
 * Custom submit for file upload.
 */
function easyddb_dams_add_upload_submit($form, $form_state) {
  // If file uploaded form DAMS page redirect to it, not to default page.
  $_GET['destination'] = 'admin/easyddb_dams_media_manager';
}
